site_name: My Docs

theme:
  name: material

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # scheme: slate
      primary: yellow
      accent: yellow 
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow 
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: zh 

  logo: canada-logo.svg
  favicon: Canada-Flag.png


  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top

    - search.highlight
    - search.share

    - header.autohide
    - navigation.footer



  plugins:
    - social:
        cards_font: Noto Sans SC
    
    - blog:
      - blog/index.md
      post_date_format: full

    - tags


  extra:
    social:
      - icon: fontawesome/brands/mastodon 
        link: https://fosstodon.org/@squidfunk
      - icon: fontawesome/solid/paper-plane
        link: mailto:<email-address>


  copyright: Copyright &copy; 2016 - 2020 Martin Donath
















   


